version: 2

updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
    groups:
      npm-root:
        patterns:
          - "*"
    commit-message:
      prefix: "chore(deps)"
    labels:
      - "dependencies"
      - "automação"

  - package-ecosystem: "npm"
    directory: "/packages/cli"
    schedule:
      interval: "weekly"
      day: "monday"
    groups:
      npm-cli:
        patterns:
          - "*"
    commit-message:
      prefix: "chore(deps)"
    labels:
      - "dependencies"
      - "automação"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
    groups:
      github-actions:
        patterns:
          - "*"
    commit-message:
      prefix: "chore(deps)"
    labels:
      - "dependencies"
      - "automação"
